Fix queue-related intermittency in producer tests
Fix another intermittency problem caused by relying on wall clock time
when testing queues in `TestProducer_WithNotifier/RegistersQueueStatus`
where they're upserted by a producer[1].

    --- FAIL: TestProducer_WithNotifier (0.00s)
        --- FAIL: TestProducer_WithNotifier/RegistersQueueStatus (7.04s)
            producer_test.go:371: Generated schema "river_2025_04_26t04_16_54_schema_15" with migrations [1 2 3 4 5 6] on line "main" in 3.056885981s [15 generated] [8 reused]
            producer_test.go:385:
                    Error Trace:	/home/runner/work/river/river/producer_test.go:385
                    Error:      	Max difference between 2025-04-26 04:17:03.800146245 +0000 UTC and 2025-04-26 04:17:06.08229 +0000 UTC allowed is 2s, but difference was -2.282143755s
                    Test:       	TestProducer_WithNotifier/RegistersQueueStatus
            logger.go:256: time=2025-04-26T04:17:06.091Z level=ERROR msg="producer: Queue status update, error updating in database" err="context canceled"
            riverdbtest.go:277: Checked in schema "river_2025_04_26t04_16_54_schema_15"; 1 idle schema(s) [15 generated] [8 reused]
    FAIL
    FAIL	github.com/riverqueue/river	34.065s

Switch over to using a version based on an injected clock and `now`.

[1] https://github.com/riverqueue/river/actions/runs/14677626265/job/41196195586