Reimplement driver tests for `PGAdvisoryXactLock` so they don't involve clock timing (#885)
I've gotten a failure a couple times in the driver tests for
`PGAdvisoryXactLock` in that it times out when trying to use another
transaction to acquire or release the lock:

    --- FAIL: TestDriverDatabaseSQLLibPQ (19.44s)
        driver_test.go:40: Generated schema "river_2025_05_08t01_05_22_schema_08" with migrations [1 2 3 4 5 6] on line "main" in 53.591381ms [9 generated] [5 reused]
        driver_test.go:40: Driver does not support listener; skipping listener tests
        --- FAIL: TestDriverDatabaseSQLLibPQ/PGAdvisoryXactLock (0.21s)
            riverdrivertest.go:2691: TestTx using schema: river_2025_05_08t01_05_22_schema_06
            riverdrivertest.go:2701: TestTx using schema: river_2025_05_08t01_05_22_schema_06
            riverdrivertest.go:2727:
                    Error Trace:	/home/runner/work/river/river/internal/riverinternaltest/riverdrivertest/riverdrivertest.go:2727
                    Error:      	Goroutine didn't finish in a timely manner
                    Test:       	TestDriverDatabaseSQLLibPQ/PGAdvisoryXactLock
        riverdbtest.go:277: Checked in schema "river_2025_05_08t01_05_22_schema_08"; 1 idle schema(s) [137 generated] [133 reused]
    FAIL
    FAIL	github.com/riverqueue/river	27.844s

Here, reimplement this test wholesale, moving away from dependency on
clock timing and over to having the other test transaction use the
non-blocking `pg_try_advisory_lock `instead. This should eliminate all
intermittency from this test case.

[1] https://github.com/riverqueue/river/actions/runs/14896356386/job/41839541488